# Generated by Django 6.0.7 on 2026-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
